import FizzBuzzMaker.FizzBuzzMaker;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
  public static void main(String[] args) {
    for (int i = 1; i <= 100; i++) {
      System.out.println(FizzBuzzMaker.makeString(i));

    }
  }
}
