package FizzBuzzChecker;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class FizzBuzzCheckerTest {
  @Test
  public void should_isFizz_return_false_given_1() {
    //given
    int given = 1;
    //when
    boolean isFizzReturn = FizzBuzzChecker.isFizz(given);
    //then
    assertThat(isFizzReturn, is(false));
  }
}
